name: flutter_example #应用或包名称
description: A new Flutter application.
version: 1.0.0+1 #版本号

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies: #应用或包依赖其他库
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.3 #添加依赖库
  flutter_staggered_grid_view: "^0.2.5" #交错GridView效果
  fluttertoast: ^2.2.2
  path_provider: ^0.4.1
  dio: ^1.0.13
  web_socket_channel: ^1.0.9

dev_dependencies: #开发环境依赖的工具包
  flutter_test:
    sdk: flutter
flutter: # flutter的相关配置
  uses-material-design: true
  assets:
    - images/icon.png
    - images/background.png